# Site settings
title: Pebbles Games
email: pebblesgames@gmail.com
description: "Pebbles Games is a new indie game studio based out of Toronto, ON. We are currently in the midst of creating our first unnamed creation, but you can follow our progress (and rants) by checking out our blog."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pebblesgames.com" # the base hostname & protocol for your site
twitter_username: AlexPennells
facebook_url: "https://www.facebook.com/pages/Pebbles-Games/739720026106837?ref=hl"
github_username:  alexpennells
paginate: 2
paginate_path: ":num/"

# Build settings
markdown: kramdown
